version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-3g!&1-%o7u$$r$$@s$$1doy16^n8hjjazdsn2h)#!vw*ufkn1c&0e
      - DEBUG=True
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - TIME_ZONE=America/New_York
      - STATIC_URL=/static/
      - MEDIA_URL=/media/
      - USE_SSL=False

volumes:
  db:
  static_files:
  media_files:
